name: build-passwall2-ipk-a53

on:
  workflow_dispatch:
    inputs:
      passwall2_tag:
        description: "Use this openwrt-passwall2 tag. Empty = Latest Release tag."
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo (packages.txt)
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential clang flex bison g++ gawk gcc-multilib gettext \
            git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip zlib1g-dev \
            file wget curl ca-certificates jq xz-utils zip

      - name: Resolve passwall2 tag (input or latest)
        id: rel
        run: |
          set -e
          IN="${{ github.event.inputs.passwall2_tag }}"
          if [ -n "$IN" ]; then
            echo "tag=$IN" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          TAG="$(curl -fsSL https://api.github.com/repos/Openwrt-Passwall/openwrt-passwall2/releases/latest | jq -r .tag_name)"
          if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
            echo "Failed to fetch latest tag" >&2
            exit 1
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Clone ImmortalWrt buildroot v21.02.7
        run: |
          set -e
          git clone --depth 1 --branch v21.02.7 https://github.com/immortalwrt/immortalwrt.git openwrt

      - name: Add feeds and pin passwall2 to tag
        run: |
          set -e
          cd openwrt

          printf '%s\n' \
            "src-git passwall2 https://github.com/Openwrt-Passwall/openwrt-passwall2.git" \
            "src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git" \
            >> feeds.conf.default

          ./scripts/feeds update passwall2
          ./scripts/feeds update passwall_packages
          ./scripts/feeds install -a -p passwall2
          ./scripts/feeds install -a -p passwall_packages

          cd feeds/passwall2
          git fetch --tags --force
          git checkout -f "${{ steps.rel.outputs.tag }}"

      - name: Select target (ipq60xx/generic or fallback mt7622)
        run: |
          set -e
          cd openwrt

          : > .config
          printf '%s\n' \
            "CONFIG_TARGET_ipq60xx=y" \
            "CONFIG_TARGET_ipq60xx_generic=y" \
            >> .config

          if make defconfig; then
            echo "Using target ipq60xx/generic"
          else
            echo "Fallback to mediatek/mt7622"
            : > .config
            printf '%s\n' \
              "CONFIG_TARGET_mediatek=y" \
              "CONFIG_TARGET_mediatek_mt7622=y" \
              >> .config
            make defconfig
          fi

      - name: Append package selections
        run: |
          set -e
          cd openwrt

          echo "CONFIG_PACKAGE_luci-app-passwall2=m" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-passwall2-zh-cn=m" >> .config

          while IFS= read -r p; do
            [ -z "$p" ] && continue
            echo "CONFIG_PACKAGE_${p}=m" >> .config
          done < ../packages.txt

          make defconfig

      - name: Build luci packages
        run: |
          set -e
          cd openwrt
          make package/feeds/passwall2/luci-app-passwall2/compile -j"$(nproc)" V=s
          make package/feeds/passwall2/luci-i18n-passwall2-zh-cn/compile -j"$(nproc)" V=s

      - name: Build dependency packages (simple-obfs-server optional)
        run: |
          set -e
          cd openwrt

          while IFS= read -r p; do
            [ -z "$p" ] && continue

            if [ "$p" = "simple-obfs-server" ]; then
              echo "optional: $p"
              # package directory is usually 'simple-obfs' (not 'simple-obfs-server')
              make package/feeds/passwall_packages/simple-obfs/compile -j"$(nproc)" V=s || true
              continue
            fi

            echo "build: $p"
            make "package/feeds/passwall_packages/${p}/compile" -j"$(nproc)" V=s
          done < ../packages.txt

      - name: Collect IPKs and create zip
        run: |
          set -e
          cd openwrt
          OUT="$PWD/out"
          mkdir -p "$OUT/deps" "$OUT/luci"

          find bin/packages -type f -name "luci-app-passwall2_*.ipk" -exec cp -f {} "$OUT/luci/" \;
          find bin/packages -type f -name "luci-i18n-passwall2-zh-cn_*.ipk" -exec cp -f {} "$OUT/luci/" \;

          while IFS= read -r p; do
            [ -z "$p" ] && continue
            find bin/packages -type f -name "${p}_*.ipk" \
              ! -name "v2ray-geoip_*" \
              ! -name "v2ray-geosite_*" \
              -exec cp -f {} "$OUT/deps/" \; || true
          done < ../packages.txt

          (cd "$OUT/deps" && zip -9 -r "../passwall_packages_ipk_aarch64_cortex-a53.zip" .)

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "ipk-${{ steps.rel.outputs.tag }}-a53"
          name: "IPK (a53) for passwall2 ${{ steps.rel.outputs.tag }}"
          body: |
            Base: ImmortalWrt v21.02.7
            passwall2 tag: ${{ steps.rel.outputs.tag }}
            Excluded: v2ray-geoip, v2ray-geosite
            Optional: simple-obfs-server (may be missing)
          files: |
            openwrt/out/passwall_packages_ipk_aarch64_cortex-a53.zip
            openwrt/out/luci/*.ipk
